=head1 NAME

zoid - a modular perl shell

=head1 SYNOPSIS

zoid [options] [-] [files]

If no options or files are given the Zoidberg shell is started in interactive
mode. Given files are evaluated as source scripts, contents of these
files are I<NOT> handled the same way as commands entered in interactive mode.
If STDIN is a pipeline input I<will> be evalluated the same as when
entered interactively. 

=head1 DESCRIPTION

Zoidberg provides a modular Perl shell written, configured, and operated entirely
in Perl. It aspires to be a fully operational login shell with all the features
one normally expects. But it also gives direct access to Perl objects and data
structures from the command line, and allows you to run Perl code within the
scope of your commandline. Although Zoidberg does not do the language
interpreting itself -- it uses perl to do this -- it supplies powerfull language
extensions aimed at creating an easy to use interface.

FIXME more technical description (above is just the freshmeat text)

=head1 OPTIONS

=over 4

=item B<-e> I<command>, B<--exec>=I<command>

Execute a string as interpreted by zoidberg. If non-interactive exits with
exit status of command string. Multiple commands may be given to build up 
a multi-line script.  Make sure to use semicolons where you would in a 
normal multiline script.

=item B<-c> I<command>, B<--command>=I<command> 

Does the same as B<--exec> but this is bound to change.

=item B<-h>, B<-u>, B<--help>, B<--usage>

Print a help message and exits.

=item B<-I>I<dir>[,I<dir>]

The specified directories are prepended to the module search path  
C<@INC>.

=item B<-i>, B<--interactive>

Start an interactive shell. This is the default if no other options are
supplied.

=item B<-l>, B<--list-conf>

List general configuration of the installation.

=item B<-V>, B<--version>

Display version information. 

=back

=head1 ENVIRONMENT

FIXME

=head1 FILES

FIXME

=head1 DIAGNOSTICS

Error messages may be issued either by B<perl> or by one any of the
modules in use. B<zoid> itself will only complain when the commandline
options are wrong. If a fatal error occurs B<zoid> will return a
non-zero exit status.

=head1 RESTRICTIONS

Source files and command input are I<NOT> interpreted in the same way.

Use B<-e> or B<-c>, do not mix them.

=head1 BUGS

Known bugs are listed in the F<BUGS> file, which is included in the source
package. Please report bugs through the bug tracker on the Sourceforce project
page L<http://sourceforge.net/projects/zoidberg> or mail pardus
E<lt>pardus@users.sf.netE<gt>.

=head1 DOCUMENTATION

More elaborate documentation on the Zoidberg shell can be found online at
L<http://zoidberg.sourceforge.net/doc> or on your local system,
by default it could be found in F</usr/local/doc/zoid/>. In interactive mode
C<help> should be available by entering the command C<help>.

=head1 SEE ALSO

L<perl(1)>, L<Zoidberg(3)>, L<http://zoidberg.sourceforge.net>

=head1 AUTHORS

Jaap Karssenberg || Pardus [Larus] E<lt>pardus@users.sf.netE<gt>

R.L. Zwart, E<lt>carl0s@users.sf.netE<gt>

=head1 COPYRIGHT

Copyright (c) 2002 Jaap G Karssenberg and RL Zwart. All 
rights reserved. This program is free software; you can 
redistribute it and/or modify it under the same terms as Perl.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

See L<http://www.perl.com/language/misc/Artistic.html> and
L<http://www.gnu.org/copyleft/gpl.html>

