=head1 Zoidberg documentation

I<Be aware: work in progres.>

=head2 Package files. 

=begin text

 * ../README
 * ../Install
 * ../Changes
 * ../TODO
 * ../BUGS

=end text

=begin html

<ul>
<li><a href='../README'>README</a></li>
<li><a href='../Install'>Install</a></li>
<li><a href='../Changes'>Changes</a></li>
<li><a href='../TODO'>TODO</a></li>
<li><a href='../BUGS'>BUGS</a></li>
</ul>

=end html

=head2 Contents

=begin text

 * user
 * devel

=end text

=begin html

<ul>
<li><a href='./user/index.html'>User manual</a></li>
<li><a href='./devel/index.html'>Developer manual</a></li>
</ul>

=end html

=head2 Man pages

I<The man pages are not installed as html by default, to install them use C<perl Makefile.PL --man2html>.>

=begin html

<ul>
<li><a href='./man1/zoid.html'>zoid(1) - the frontend script for the Zoidberg shell</a></li>
<li><a href='./man3pm/'>man 3pm - Perl modules</a></li>
</ul>

=end html

=cut
