#!/bin/sh
################################################################
# This is the uninstall script for the zoidberg program files. #
# This script was autogenerated by the install.pl script       #
#                                                              #
# mailto:j.g.karssenberg@student.utwente.nl                    #
# http://zoidberg.sourceforge.net                              #
################################################################
rm -f /usr/local/bin/zoid &&
echo "removed /usr/local/bin/zoid" ;
rm -f /etc/zoid/char-table.pd &&
echo "removed /etc/zoid/char-table.pd" ;
rm -f /etc/zoid/core.pd &&
echo "removed /etc/zoid/core.pd" ;
rm -f /etc/zoid/grammar.pd &&
echo "removed /etc/zoid/grammar.pd" ;
rm -f /etc/zoid/monitor.pd &&
echo "removed /etc/zoid/monitor.pd" ;
rm -f /etc/zoid/profile.pd &&
echo "removed /etc/zoid/profile.pd" ;
rm -f /etc/zoid/ps1.pd &&
echo "removed /etc/zoid/ps1.pd" ;
rm -f /usr/local/share/zoid/MOTZ/zoidberg_fortune &&
echo "removed /usr/local/share/zoid/MOTZ/zoidberg_fortune" ;
rm -f /usr/local/share/zoid/help/Configuration.pod &&
echo "removed /usr/local/share/zoid/help/Configuration.pod" ;
rm -f /usr/local/share/zoid/help/Syntax.pod &&
echo "removed /usr/local/share/zoid/help/Syntax.pod" ;
rm -f /usr/local/share/zoid/help/Zoidscript.pod &&
echo "removed /usr/local/share/zoid/help/Zoidscript.pod" ;
rm -f /usr/local/share/zoid/help/Zoidberg/Commands.pod &&
echo "removed /usr/local/share/zoid/help/Zoidberg/Commands.pod" ;
rm -f /usr/local/share/zoid/help/Zoidberg/Monitor.pod &&
echo "removed /usr/local/share/zoid/help/Zoidberg/Monitor.pod" ;
rm -f /usr/local/share/zoid/pixmaps/zoid16.png &&
echo "removed /usr/local/share/zoid/pixmaps/zoid16.png" ;
rm -f /usr/local/share/zoid/pixmaps/zoid32.png &&
echo "removed /usr/local/share/zoid/pixmaps/zoid32.png" ;
rm -f /usr/local/share/zoid/pixmaps/zoid64.png &&
echo "removed /usr/local/share/zoid/pixmaps/zoid64.png" ;
rm -f /usr/local/share/zoid/scripts/demo.zs &&
echo "removed /usr/local/share/zoid/scripts/demo.zs" ;
rm -f /usr/local/share/doc/zoid/Configuration.html &&
echo "removed /usr/local/share/doc/zoid/Configuration.html" ;
rm -f /usr/local/share/doc/zoid/Syntax.html &&
echo "removed /usr/local/share/doc/zoid/Syntax.html" ;
rm -f /usr/local/share/doc/zoid/Zoidscript.html &&
echo "removed /usr/local/share/doc/zoid/Zoidscript.html" ;
rm -f /usr/local/share/doc/zoid/Zoidberg/Commands.html &&
echo "removed /usr/local/share/doc/zoid/Zoidberg/Commands.html" ;
rm -f /usr/local/share/doc/zoid/Zoidberg/Monitor.html &&
echo "removed /usr/local/share/doc/zoid/Zoidberg/Monitor.html" ;
rm -f /usr/local/share/doc/zoid/index.html &&
echo "removed /usr/local/share/doc/zoid/index.html" ;
