=head1 CONFIGURATION

=head2 Files

The location of files can be installation specific. You can check the location 
where zoid looks for them with the command C<zoid --list-conf>.
All global configuration can by default be found in your home directory 
in F<~/.zoid> ("config_dir"), some plugins also put data files in this dir.
Plugins have seperate config files that are hashed by zoidberg, they can be
found in F<~/.zoid/plugins> ("plugins_dir").

The most important is the settings_file, is contains the main settings hash.
( Note that this file might get incorporated in F<~/.zoidrc>. )

=head2 Data Structures

=over 4

=item settings

This hash can at all times be accessed from the command line.
Also the builtin C<set> command acts on thsi hash. See SETTINGS
for a summary of it's keys.

FIXME Where are special builtins documented ?

=item plugins

This hash is a representation of the seperate plugin configuration files. Most
of it's information is referenced by the plugins, so it could be harmfull to 
edit it. When you edit a plugin configuration file, you probably only wnat to
edit the "config" section, this is the configuration for the plugin - other
fields in the file contain meta information about the plugin for zoidberg.

FIXME Where is documentation about the plugin system to be found ?

=item 

=back

