=head1 SETTINGS

The following settings supported by (some) Zoidberg modules.

=head2 Common Settings

=over 4

=item allow_null_glob_expansion

It allows to have wildcard patterns that expand into an empty list.
The default behaviour is to leave the pattern unchanged  
when it  is  syntactically  incorrect,  or the list of matching pathnames is empty.  

=item noglob

Disable path expansion for shell-like syntax.

=item hide_private_method

Hide all object methods and data structures which have a name starting with an '_'
unless they are asked for explicitly.

=item hide_hidden_files

Hide all filesystem nodes which have a name starting with a '.'
unless they are asked for explicitly.

=back

=head2 Devel Settings

=item _no_redirection

Disable builtin parsing for redirections. Probably needed if you want to do this yourself.

=item _no_hardcoded_context

Disable hardcoded contexts like PERL, SH and CMD. This might be usefull
to make for example a restricted shell.

=back

