=head1 DESCRIPTION

The general structure of the Zoidberg shell has three kinds of 
objects: the engine, the plugins and libraries.

=over 4

=item Engine

=over 4

=item * Zoidberg:	Main object, event and plugin management

=item * ZoidParse:	Parsing, Job control & POSIX stuff

=item * Eval:		Namespace for command execution

=back

=item Libraries

=over 4

=item * FileRoutines:	File handling routines

=item * StringParse:	Simple syntax parser

=item * Error:		Object Oriented error handling

=item * DistpatchTable:	enforces zoid's dispatch style

=back

=item Plugins

=over 4

=item * Fish:		Base class for plugins

=item * Core objects:	Provides default interface.

=item * User defined:	extensions

=back

=back

=head2 Sheme

                 StringParse
                     |
                  ZoidParse
                     |
                     |
                     |
 zoid       ____  Zoidberg _____ Eval
 executable       Engine
                     |
                     |
                     |___ Plugins
                     |
                     |___ Config Hashes *
                     |___ Events *
                     |___ Builtin Commands *
 
 *) These are partially shared with the plugins

=head1 ENGINE

=head2 Configuration

TODO

=head2 Events

TODO

=head1 LIBRARIES

TODO

=head1 PLUGINS

TODO

